// Item types, names, and ids
module.exports = {
  primary: [
    'Armor',
    'Shields',
    'Melee Weapons',
    'Ranged Weapons',
    'Staves',
    'Jewelry',
    'Class Items',
    'Miscellaneous',
  ],
  quality: [
    'All',
    'Normal',
    'Exceptional',
    'Elite',
  ],
  rarity: [
    'Normal',
    'Set',
    'Unique',
  ],
  Armor: [
    'Belts',
    'Body Armor',
    'Boots',
    'Gloves',
    'Helms',
    'Circlets',
  ],
  Shields: [
    'Shields',
    'Paladin Shields',
    'Necromancer Totems',
  ],
  'Melee Weapons': [
    'Axes',
    'Daggers',
    'Maces',
    'Polearms',
    'Scepters',
    'Spears',
    'Swords',
  ],
  'Ranged Weapons': [
    'Bows',
    'Crossbows',
    'Javelins',
    'Throwing Weapons',
  ],
  Staves: [
    'Staves',
    'Wands',
    'Sorceress Orbs',
  ],
  Jewelry: [
    'No subtypes',
  ],
  'Class Items': [
    'Amazon Weapons',
    'Assassin Claws',
    'Barbarian Helms',
    'Druid Helms',
    'Necromancer Totems',
    'Paladin Shields',
    'Sorceress Orbs',
  ],
  Miscellaneous: [
    'Runes',
    'Gems',
    'Potions',
    'Scrolls',
    'Tomes',
    'Other',
  ],
  BeltsNormalNormal: [
    { name: 'Sash', id: 'lbl' },
    { name: 'Light Belt', id: 'vbl' },
    { name: 'Belt', id: 'mbl' },
    { name: 'Heavy Belt', id: 'tbl' },
    { name: 'Plated Belt', id: 'hbl' },
  ],
  BeltsExceptionalNormal: [
    { name: 'Demonhide Sash', id: 'zlb' },
    { name: 'Sharkskin Belt', id: 'zvb' },
    { name: 'Mesh Belt', id: 'zmb' },
    { name: 'Battle Belt', id: 'ztb' },
    { name: 'War Belt', id: 'zhb' },
  ],
  BeltsEliteNormal: [
    { name: 'Spiderweb Sash', id: 'ulc' },
    { name: 'Vampirefang Belt', id: 'uvc' },
    { name: 'Mithril Coil', id: 'umc' },
    { name: 'Troll Belt', id: 'utc' },
    { name: 'Colossus Girdle', id: 'uhc' },
  ],
  BeltsNormalSet: [
    { name: 'Arctic Binding', id: '56' },
    { name: 'Death\'s Guard', id: '48' },
    { name: 'Hsaru\'s Iron Stay', id: '5' },
    { name: 'Infernal Sign', id: '43' },
    { name: 'Iratha\'s Cord', id: '12' },
    { name: 'Hwanin\'s Blessing', id: '110' },
    { name: 'Sigon\'s Wrap', id: '39' },
  ],
  BeltsExceptionalSet: [
    { name: 'Immortal King\'s Detail', id: '72' },
    { name: 'M\'avina\'s Tenet', id: '93' },
    { name: 'Tal Rasha\'s Fine Spun Cloth', id: '76' },
    { name: 'Wilhelm\'s Pride', id: '105' },
  ],
  BeltsEliteSet: [
    { name: 'Credendum', id: '99' },
    { name: 'Trang-Oul\'s Girth', id: '89' },
  ],
  BeltsNormalUnique: [
    { name: 'Lenymo', id: '112' },
    { name: 'Snakecord', id: '113' },
    { name: 'Nightsmoke', id: '114' },
    { name: 'Goldwrap', id: '115' },
    { name: 'Bladebuckle', id: '116' },
  ],
  BeltsExceptionalUnique: [
    { name: 'String of Ears', id: '242' },
    { name: 'Razortail', id: '243' },
    { name: 'Gloom\'s Trap', id: '244' },
    { name: 'Snowclash', id: '245' },
    { name: 'Thundergod\'s Vigor', id: '246' },
  ],
  BeltsEliteUnique: [
    { name: 'Arachnid Mesh', id: '373' },
    { name: 'Nosferatu\'s Coil', id: '374' },
    { name: 'Verdungo\'s Hearty Cord', id: '376' },
  ],
  'Body ArmorNormalNormal': [
    { name: 'Quilted Armor', id: 'qui' },
    { name: 'Leather Armor', id: 'lea' },
    { name: 'Hard Leather Armor', id: 'hla' },
    { name: 'Studded Leather', id: 'stu' },
    { name: 'Ring Mail', id: 'rng' },
    { name: 'Scale Mail', id: 'scl' },
    { name: 'Breast Plate', id: 'brs' },
    { name: 'Chain Mail', id: 'chn' },
    { name: 'Splint Mail', id: 'spl' },
    { name: 'Light Plate', id: 'ltp' },
    { name: 'Field Plate', id: 'fld' },
    { name: 'Plate Mail', id: 'plt' },
    { name: 'Gothic Plate', id: 'gth' },
    { name: 'Full Plate Mail', id: 'ful' },
    { name: 'Ancient Armor', id: 'aar' },
  ],
  'Body ArmorExceptionalNormal': [
    { name: 'Ghost Armor', id: 'xui' },
    { name: 'Serpentskin Armor', id: 'xea' },
    { name: 'Demonhide Armor', id: 'xla' },
    { name: 'Trellised Leather', id: 'xtu' },
    { name: 'Linked Mail', id: 'xng' },
    { name: 'Tigulated Mail', id: 'xcl' },
    { name: 'Cuirass', id: 'xrs' },
    { name: 'Mesh Armor', id: 'xhn' },
    { name: 'Russet Armor', id: 'xpl' },
    { name: 'Mage Plate', id: 'xtp' },
    { name: 'Sharktooth Armor', id: 'xld' },
    { name: 'Templar Coat', id: 'xlt' },
    { name: 'Embossed Plate', id: 'xth' },
    { name: 'Chaos Armor', id: 'xul' },
    { name: 'Ornate Plate', id: 'xar' },
  ],
  'Body ArmorEliteNormal': [
    { name: 'Dusk Shroud', id: 'uui' },
    { name: 'Wyrmhide', id: 'uea' },
    { name: 'Scarab Husk', id: 'ula' },
    { name: 'Wire Fleece', id: 'utu' },
    { name: 'Diamond Mail', id: 'ung' },
    { name: 'Loricated Mail', id: 'ucl' },
    { name: 'Great Hauberk', id: 'urs' },
    { name: 'Boneweave', id: 'uhn' },
    { name: 'Balrog Skin', id: 'upl' },
    { name: 'Archon Plate', id: 'utp' },
    { name: 'Kraken Shell', id: 'uld' },
    { name: 'Hellforge Plate', id: 'ult' },
    { name: 'Lacquered Plate', id: 'uth' },
    { name: 'Shadow Plate', id: 'uul' },
    { name: 'Sacred Armor', id: 'uar' },
  ],
  'Body ArmorNormalSet': [
    { name: 'Angelic Mantle', id: '51' },
    { name: 'Arcanna\'s Flesh', id: '61' },
    { name: 'Arctic Furs', id: '55' },
    { name: 'Berserker\'s Hauberk', id: '45' },
    { name: 'Cathan\'s Mesh', id: '26' },
    { name: 'Isenhart\'s Case', id: '15' },
    { name: 'Milabrega\'s Robe', id: '24' },
    { name: 'Sigon\'s Shelter', id: '37' },
    { name: 'Tancred\'s Spine', id: '31' },
    { name: 'Vidala\'s Ambush', id: '19' },
    { name: 'Cow King\'s Hide', id: '118' },
  ],
  'Body ArmorExceptionalSet': [
    { name: 'Aldur\'s Deception', id: '67' },
    { name: 'Griswold\'s Heart', id: '82' },
    { name: 'Haemosu\'s Adament', id: '102' },
    { name: 'Hwanin\'s Refuge', id: '109' },
    { name: 'Trang-Oul\'s Scales', id: '86' },
  ],
  'Body ArmorEliteSet': [
    { name: 'Immortal King\'s Soul Cage', id: '71' },
    { name: 'M\'avina\'s Embrace', id: '91' },
    { name: 'Naj\'s Light Plate', id: '121' },
    { name: 'Natalya\'s Shadow', id: '64' },
    { name: 'Sazabi\'s Ghost Liberator', id: '113' },
    { name: 'Tal Rasha\'s Guardianship', id: '79' },
  ],
  'Body ArmorNormalUnique': [
    { name: 'Greyform', id: '79' },
    { name: 'Blinkbat\'s Form', id: '80' },
    { name: 'The Centurion', id: '81' },
    { name: 'Twitchthroe', id: '82' },
    { name: 'Darkglow', id: '83' },
    { name: 'Hawkmail', id: '84' },
    { name: 'Sparking Mail', id: '85' },
    { name: 'Venom Ward', id: '86' },
    { name: 'Iceblink', id: '87' },
    { name: 'Boneflesh', id: '88' },
    { name: 'Rattlecage', id: '89' },
    { name: 'Rockfleece', id: '90' },
    { name: 'Goldskin', id: '91' },
    { name: 'Silks of the Victor', id: '92' },
    { name: 'Heavenly Garb', id: '93' },
  ],
  'Body ArmorExceptionalUnique': [
    { name: 'The Spirit Shroud', id: '209' },
    { name: 'Skin of the Vipermagi', id: '210' },
    { name: 'Skin of the Flayed One', id: '211' },
    { name: 'Iron Pelt', id: '212' },
    { name: 'Spirit Forge', id: '213' },
    { name: 'Crow Caw', id: '214' },
    { name: 'Shaftstop', id: '215' },
    { name: 'Duriel\'s Shell', id: '216' },
    { name: 'Skullder\'s Ire', id: '217' },
    { name: 'Guardian Angel', id: '218' },
    { name: 'Toothrow', id: '219' },
    { name: 'Que-Hegan\'s Wisdom', id: '223' },
    { name: 'Atma\'s Wail', id: '220' },
    { name: 'Black Hades', id: '221' },
    { name: 'Corpsemourn', id: '222' },
  ],
  'Body ArmorEliteUnique': [
    { name: 'Leviathan', id: '317' },
    { name: 'Ormus\' Robes', id: '358' },
    { name: 'Steel Carapace', id: '348' },
    { name: 'The Gladiator\'s Bane', id: '250' },
    { name: 'Arkaine\'s Valor', id: '251' },
    { name: 'Templar\'s Might', id: '366' },
    { name: 'Tyrael\'s Might', id: '311' },
  ],
  GlovesNormalSet: [
    { name: 'Arctic Mitts', id: '57' },
    { name: 'Cleglaw\'s Pincers', id: '8' },
    { name: 'Death\'s Hand', id: '47' },
    { name: 'Iratha\'s Cuff', id: '10' },
  ],
  Runes: [
    { name: 'El Rune', id: 'r01' },
    { name: 'Eld Rune', id: 'r02' },
    { name: 'Tir Rune', id: 'r03' },
    { name: 'Nef Rune', id: 'r04' },
    { name: 'Eld Rune', id: 'r05' },
    { name: 'Ith Rune', id: 'r06' },
    { name: 'Tal Rune', id: 'r07' },
    { name: 'Ral Rune', id: 'r08' },
    { name: 'Ort Rune', id: 'r09' },
    { name: 'Thul Rune', id: 'r10' },
    { name: 'Amn Rune', id: 'r11' },
    { name: 'Sol Rune', id: 'r12' },
    { name: 'Shael Rune', id: 'r13' },
    { name: 'Dol Rune', id: 'r14' },
    { name: 'Hel Rune', id: 'r15' },
    { name: 'Io Rune', id: 'r16' },
    { name: 'Lum Rune', id: 'r17' },
    { name: 'Ko Rune', id: 'r18' },
    { name: 'Fal Rune', id: 'r19' },
    { name: 'Lem Rune', id: 'r20' },
    { name: 'Pul Rune', id: 'r21' },
    { name: 'Um Rune', id: 'r22' },
    { name: 'Mal Rune', id: 'r23' },
    { name: 'Ist Rune', id: 'r24' },
    { name: 'Gul Rune', id: 'r25' },
    { name: 'Vex Rune', id: 'r26' },
    { name: 'Ohm Rune', id: 'r27' },
    { name: 'Lo Rune', id: 'r28' },
    { name: 'Sur Rune', id: 'r29' },
    { name: 'Ber Rune', id: 'r30' },
    { name: 'Jah Rune', id: 'r31' },
    { name: 'Cham Rune', id: 'r32' },
    { name: 'Zod Rune', id: 'r33' },
  ],
  Gems: [
    { name: 'Chipped Amethyst', id: 'gcv' },
    { name: 'Chipped Diamond', id: 'gcw' },
    { name: 'Chipped Emerald', id: 'gcg' },
    { name: 'Chipped Ruby', id: 'gcr' },
    { name: 'Chipped Sapphire', id: 'gcb' },
    { name: 'Chipped Skull', id: 'skc' },
    { name: 'Chipped Topaz', id: 'gcy' },
    { name: 'Flawed Amethyst', id: 'gfv' },
    { name: 'Flawed Diamond', id: 'gfw' },
    { name: 'Flawed Emerald', id: 'gfg' },
    { name: 'Flawed Ruby', id: 'gfr' },
    { name: 'Flawed Sapphire', id: 'gfb' },
    { name: 'Flawed Skull', id: 'skf' },
    { name: 'Flawed Topaz', id: 'gfy' },
    { name: 'Amethyst', id: 'gsv' },
    { name: 'Diamond', id: 'gsw' },
    { name: 'Emerald', id: 'gsg' },
    { name: 'Ruby', id: 'gsr' },
    { name: 'Sapphire', id: 'gsb' },
    { name: 'Skull', id: 'sku' },
    { name: 'Topaz', id: 'gsy' },
    { name: 'Flawless Amethyst', id: 'gzv' },
    { name: 'Flawless Diamond', id: 'glw' },
    { name: 'Flawless Emerald', id: 'glg' },
    { name: 'Flawless Ruby', id: 'glr' },
    { name: 'Flawless Sapphire', id: 'glb' },
    { name: 'Flawless Skull', id: 'skl' },
    { name: 'Flawless Topaz', id: 'gly' },
    { name: 'Perfect Amethyst', id: 'gpv' },
    { name: 'Perfect Diamond', id: 'gpw' },
    { name: 'Perfect Emerald', id: 'gpg' },
    { name: 'Perfect Ruby', id: 'gpr' },
    { name: 'Perfect Sapphire', id: 'gpb' },
    { name: 'Perfect Skull', id: 'skz' },
    { name: 'Perfect Topaz', id: 'gpy' },
  ],
  Potions: [
    { name: 'Lesser Healing Potion', id: 'hp1' },
    { name: 'Lesser Mana Potion', id: 'mp1' },
    { name: 'Light Healing Potion', id: 'hp2' },
    { name: 'Light Mana Potion', id: 'mp2' },
    { name: 'Healing Potion', id: 'hp3' },
    { name: 'Mana Potion', id: 'mp3' },
    { name: 'Strong Healing Potion', id: 'hp4' },
    { name: 'Strong Mana Potion', id: 'mp4' },
    { name: 'Greater Healing Potion', id: 'hp5' },
    { name: 'Greater Mana Potion', id: 'mp5' },
    { name: 'Rejuvenation Potion', id: 'rvs' },
    { name: 'Full Rejuvenation Potion', id: 'rvl' },
  ],
  Scrolls: [
    { name: 'Identity Scroll', id: 'isc' },
    { name: 'Town Portal Scroll', id: 'tsc' },
  ],
  Tomes: [
    { name: 'Identify Book', id: 'ibk' },
    { name: 'Town Portal Book', id: 'tbk' },
  ],
  Other: [
    { name: 'Burning Essence of Terror', id: 'bet' },
    { name: 'Charged Essence of Hatred', id: 'ceh' },
    { name: 'Festering Essence of Destruction', id: 'fed' },
    { name: 'Twisted Essence of Suffering', id: 'tes' },
    { name: 'Token of Absolution', id: 'toa' },
    { name: 'Key of Hate', id: 'pk1' },
    { name: 'Key of Terror', id: 'pk2' },
    { name: 'Key of Destruction', id: 'pk3' },
  ],
};
