// Item types, names, and ids
module.exports = {
  primary: [
    'Armor',
    'Shields',
    'Melee Weapons',
    'Ranged Weapons',
    'Staves',
    'Jewelry',
    'Class Items',
    'Miscellaneous',
  ],
  quality: [
    'Normal',
    'Exceptional',
    'Elite',
  ],
  rarity: [
    'Normal',
    'Set',
    'Unique',
  ],
  Armor: [
    'Belts',
    'Body Armor',
    'Boots',
    'Gloves',
    'Helms',
    'Circlets',
  ],
  Shields: [
    'Shields',
    'Paladin Shields',
    'Necromancer Totems',
  ],
  'Melee Weapons': [
    'Axes',
    'Daggers',
    'Maces',
    'Polearms',
    'Scepters',
    'Spears',
    'Swords',
  ],
  'Ranged Weapons': [
    'Bows',
    'Crossbows',
    'Javelins',
    'Throwing Weapons',
  ],
  Staves: [
    'Staves',
    'Wands',
    'Sorceress Orbs',
  ],
  Jewelry: [
    'No subtypes',
  ],
  'Class Items': [
    'Amazon Weapons',
    'Assassin Claws',
    'Barbarian Helms',
    'Druid Helms',
    'Necromancer Totems',
    'Paladin Shields',
    'Sorceress Orbs',
  ],
  Miscellaneous: [
    'Runes',
    'Gems',
    'Potions',
    'Tomes',
    'Other',
  ],
  BeltsNormalNormal: [
    { name: 'Sash', id: 'lbl' },
    { name: 'Light Belt', id: 'vbl' },
    { name: 'Belt', id: 'mbl' },
    { name: 'Heavy Belt', id: 'tbl' },
    { name: 'Plated Belt', id: 'hbl' },
  ],
  BeltsExceptionalNormal: [
    { name: 'Demonhide Sash', id: 'zlb' },
    { name: 'Sharkskin Belt', id: 'zvb' },
    { name: 'Mesh Belt', id: 'zmb' },
    { name: 'Battle Belt', id: 'ztb' },
    { name: 'War Belt', id: 'zhb' },
  ],
  BeltsEliteNormal: [
    { name: 'Spiderweb Sash', id: 'ulc' },
    { name: 'Vampirefang Belt', id: 'uvc' },
    { name: 'Mithril Coil', id: 'umc' },
    { name: 'Troll Belt', id: 'utc' },
    { name: 'Colossus Girdle', id: 'uhc' },
  ],
  BeltsNormalSet: [
    { name: 'Arctic Binding', id: '56' },
    { name: 'Death\'s Guard', id: '48' },
    { name: 'Hsaru\'s Iron Stay', id: '5' },
    { name: 'Infernal Sign', id: '43' },
    { name: 'Iratha\'s Cord', id: '12' },
    { name: 'Hwanin\'s Blessing', id: '110' },
    { name: 'Sigon\'s Wrap', id: '39' },
  ],
  BeltsExceptionalSet: [
    { name: 'Immortal King\'s Detail', id: '72' },
    { name: 'M\'avina\'s Tenet', id: '93' },
    { name: 'Tal Rasha\'s Fine Spun Cloth', id: '76' },
    { name: 'Wilhelm\'s Pride', id: '105' },
  ],
  BeltsEliteSet: [
    { name: 'Credendum', id: '99' },
    { name: 'Trang-Oul\'s Girth', id: '89' },
  ],
  BeltsNormalUnique: [
    { name: 'Lenymo', id: '112' },
    { name: 'Snakecord', id: '113' },
    { name: 'Nightsmoke', id: '114' },
    { name: 'Goldwrap', id: '115' },
    { name: 'Bladebuckle', id: '116' },
  ],
  BeltsExceptionalUnique: [
    { name: 'String of Ears', id: '242' },
    { name: 'Razortail', id: '243' },
    { name: 'Gloom\'s Trap', id: '244' },
    { name: 'Snowclash', id: '245' },
    { name: 'Thundergod\'s Vigor', id: '246' },
  ],
  BeltsEliteUnique: [
    { name: 'Arachnid Mesh', id: '373' },
    { name: 'Nosferatu\'s Coil', id: '374' },
    { name: 'Verdungo\'s Hearty Cord', id: '376' },
  ],
  GlovesNormalSet: [
    { name: 'Arctic Mitts', id: '57' },
    { name: 'Cleglaw\'s Pincers', id: '8' },
    { name: 'Death\'s Hand', id: '47' },
    { name: 'Iratha\'s Cuff', id: '10' },
  ],
  Runes: [
    { name: 'El Rune', id: 'r01' },
    { name: 'Eld Rune', id: 'r02' },
    { name: 'Tir Rune', id: 'r03' },
    { name: 'Nef Rune', id: 'r04' },
    { name: 'Eld Rune', id: 'r05' },
    { name: 'Ith Rune', id: 'r06' },
    { name: 'Tal Rune', id: 'r07' },
    { name: 'Ral Rune', id: 'r08' },
    { name: 'Ort Rune', id: 'r09' },
    { name: 'Thul Rune', id: 'r10' },
    { name: 'Amn Rune', id: 'r11' },
    { name: 'Sol Rune', id: 'r12' },
    { name: 'Shael Rune', id: 'r13' },
    { name: 'Dol Rune', id: 'r14' },
    { name: 'Hel Rune', id: 'r15' },
    { name: 'Io Rune', id: 'r16' },
    { name: 'Lum Rune', id: 'r17' },
    { name: 'Ko Rune', id: 'r18' },
    { name: 'Fal Rune', id: 'r19' },
    { name: 'Lem Rune', id: 'r20' },
    { name: 'Pul Rune', id: 'r21' },
    { name: 'Um Rune', id: 'r22' },
    { name: 'Mal Rune', id: 'r23' },
    { name: 'Ist Rune', id: 'r24' },
    { name: 'Gul Rune', id: 'r25' },
    { name: 'Vex Rune', id: 'r26' },
    { name: 'Ohm Rune', id: 'r27' },
    { name: 'Lo Rune', id: 'r28' },
    { name: 'Sur Rune', id: 'r29' },
    { name: 'Ber Rune', id: 'r30' },
    { name: 'Jah Rune', id: 'r31' },
    { name: 'Cham Rune', id: 'r32' },
    { name: 'Zod Rune', id: 'r33' },
  ],
  Gems: [
    { name: 'Chipped Amethyst', id: 'gcv' },
    { name: 'Chipped Diamond', id: 'gcw' },
    { name: 'Chipped Emerald', id: 'gcg' },
    { name: 'Chipped Ruby', id: 'gcr' },
    { name: 'Chipped Sapphire', id: 'gcb' },
    { name: 'Chipped Skull', id: 'skc' },
    { name: 'Chipped Topaz', id: 'gcy' },
    { name: 'Flawed Amethyst', id: 'gfv' },
    { name: 'Flawed Diamond', id: 'gfw' },
    { name: 'Flawed Emerald', id: 'gfg' },
    { name: 'Flawed Ruby', id: 'gfr' },
    { name: 'Flawed Sapphire', id: 'gfb' },
    { name: 'Flawed Skull', id: 'skf' },
    { name: 'Flawed Topaz', id: 'gfy' },
    { name: 'Amethyst', id: 'gsv' },
    { name: 'Diamond', id: 'gsw' },
    { name: 'Emerald', id: 'gsg' },
    { name: 'Ruby', id: 'gsr' },
    { name: 'Sapphire', id: 'gsb' },
    { name: 'Skull', id: 'sku' },
    { name: 'Topaz', id: 'gsy' },
    { name: 'Flawless Amethyst', id: 'gzv' },
    { name: 'Flawless Diamond', id: 'glw' },
    { name: 'Flawless Emerald', id: 'glg' },
    { name: 'Flawless Ruby', id: 'glr' },
    { name: 'Flawless Sapphire', id: 'glb' },
    { name: 'Flawless Skull', id: 'skl' },
    { name: 'Flawless Topaz', id: 'gly' },
    { name: 'Perfect Amethyst', id: 'gpv' },
    { name: 'Perfect Diamond', id: 'gpw' },
    { name: 'Perfect Emerald', id: 'gpg' },
    { name: 'Perfect Ruby', id: 'gpr' },
    { name: 'Perfect Sapphire', id: 'gpb' },
    { name: 'Perfect Skull', id: 'skz' },
    { name: 'Perfect Topaz', id: 'gpy' },
  ],
  Potions: [
    { name: 'Lesser Healing Potion', id: 'hp1' },
    { name: 'Lesser Mana Potion', id: 'mp1' },
    { name: 'Light Healing Potion', id: 'hp2' },
    { name: 'Light Mana Potion', id: 'mp2' },
    { name: 'Healing Potion', id: 'hp3' },
    { name: 'Mana Potion', id: 'mp3' },
    { name: 'Strong Healing Potion', id: 'hp4' },
    { name: 'Strong Mana Potion', id: 'mp4' },
    { name: 'Greater Healing Potion', id: 'hp5' },
    { name: 'Greater Mana Potion', id: 'mp5' },
    { name: 'Rejuvenation Potion', id: 'rvs' },
    { name: 'Full Rejuvenation Potion', id: 'rvl' },
  ],
  Tomes: [
    { name: 'Identify Book', id: 'ibk' },
    { name: 'Town Portal Book', id: 'tbk' },
  ],
  Other: [
    { name: 'Burning Essence of Terror', id: 'bet' },
    { name: 'Charged Essence of Hatred', id: 'ceh' },
    { name: 'Festering Essence of Destruction', id: 'fed' },
    { name: 'Twisted Essence of Suffering', id: 'tes' },
    { name: 'Token of Absolution', id: 'toa' },
    { name: 'Key of Hate', id: 'pk1' },
    { name: 'Key of Terror', id: 'pk2' },
    { name: 'Key of Destruction', id: 'pk3' },
  ],
};
