// Item types, names, and ids
module.exports = {
  primary: [
    'Armor',
    'Shields',
    'Melee Weapons',
    'Ranged Weapons',
    'Staves',
    'Jewelry',
    'Class Items',
    'Miscellaneous',
  ],
  quality: [
    'Normal',
    'Exceptional',
    'Elite',
  ],
  rarity: [
    'Normal',
    'Set',
    'Unique',
    'Runeword',
    'Inferior',
  ],
  Armor: [
    'Belts',
    'Body Armor',
    'Boots',
    'Gloves',
    'Helms',
    'Circlets',
  ],
  Shields: [
    'Shields',
    'Paladin Shields',
    'Necromancer Totems',
  ],
  'Melee Weapons': [
    'Axes',
    'Daggers',
    'Maces',
    'Polearms',
    'Scepters',
    'Spears',
    'Swords',
  ],
  'Ranged Weapons': [
    'Bows',
    'Crossbows',
    'Javelins',
    'Throwing Weapons',
  ],
  Staves: [
    'Staves',
    'Wands',
    'Sorceress Orbs',
  ],
  Jewelry: [
    'No subtypes',
  ],
  'Class Items': [
    'Amazon Weapons',
    'Assassin Claws',
    'Barbarian Helms',
    'Druid Helms',
    'Necromancer Totems',
    'Paladin Shields',
    'Sorceress Orbs',
  ],
  Miscellaneous: [
    'Runes',
    'Gems',
    'Potions',
    'Tomes',
    'Other',
  ],
};
